import { state, removeFromCart, confirmCart } from '../state/store.js';
import { formatPrice } from '../utils/format.js';
import { renderMyEvents } from './myEvents.js';

export function renderCart(){
  const panel = document.querySelector('#tab-mycart'); if(!panel) return; const container = panel.querySelector('.cart-content'); if(!container) return; container.innerHTML = '';
  if(state.cart.length === 0){ container.textContent = 'Your cart is empty.'; return; }
  state.cart.forEach(entry =>{ const ev = state.events.find(e=>e.id===entry.eventId) || {title:'Unknown'}; const row = document.createElement('div'); row.className='cart-row card'; row.style.display='flex'; row.style.justifyContent='space-between'; row.style.alignItems='center'; row.style.padding='12px'; const info = document.createElement('div'); info.innerHTML = `<strong>${ev.title}</strong><div class="text-muted">Role: ${entry.role}</div>`; const actions = document.createElement('div'); const remove = document.createElement('button'); remove.className='btn'; remove.textContent='Remove'; remove.addEventListener('click', ()=>{ removeFromCart(entry.eventId); renderCart(); document.querySelectorAll('.event-card').forEach(c=>{ if(c.dataset.id===entry.eventId){ c.classList.remove('in-cart'); c.querySelectorAll('.register-btn').forEach(b=>b.removeAttribute('disabled')); const lbl = c.querySelector('.in-cart-label'); if(lbl) lbl.remove(); } }); }); actions.appendChild(remove); row.appendChild(info); row.appendChild(actions); container.appendChild(row); });

  // summary
  const summary = document.createElement('div'); summary.className='cart-summary card mt-16'; summary.style.padding='18px'; const infoWrap = document.createElement('div'); infoWrap.style.display='flex'; infoWrap.style.justifyContent='space-between'; infoWrap.style.alignItems='center'; const left = document.createElement('div'); left.innerHTML = `<strong>Cart Summary</strong><div class="text-muted">You will receive QR codes for each event after confirmation</div>`; const right = document.createElement('div'); right.style.textAlign='right'; const count = document.createElement('div'); count.className='text-muted'; count.textContent = state.cart.length + ' events'; const total = document.createElement('div'); total.style.fontWeight='700'; total.style.fontSize='1.1rem'; const totalPrice = state.cart.reduce((sum,e)=>{ const ev=state.events.find(x=>x.id===e.eventId); return sum + (ev && ev.price? ev.price:0);},0); total.textContent = formatPrice(totalPrice); right.appendChild(count); right.appendChild(total); infoWrap.appendChild(left); infoWrap.appendChild(right); const confirmRow = document.createElement('div'); confirmRow.style.marginTop='12px'; const confirmBtn = document.createElement('button'); confirmBtn.className='btn btn-primary confirm-btn'; confirmBtn.textContent='Confirm Registration'; confirmBtn.addEventListener('click', ()=>{ confirmCart(); renderCart(); renderMyEvents(); document.querySelector('.tabs .tab[data-tab="myevents"]')?.click(); }); confirmRow.appendChild(confirmBtn); summary.appendChild(infoWrap); summary.appendChild(confirmRow); container.appendChild(summary);
}
