CREATE DATABASE QreateFlow;
USE QreateFlow;

CREATE TABLE roles(
id INTEGER AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL
);

CREATE TABLE location(
id INTEGER AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
address VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE category(
id INTEGER AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(225) NOT NULL
);

CREATE TABLE events(
id INTEGER AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(225) NOT NULL,
date_time DATETIME NOT NULL,
capacity INTEGER NOT NULL,
description TEXT,
id_category INTEGER,
created_at DATE NOT NULL DEFAULT (CURRENT_DATE),
update_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
id_location INTEGER,
FOREIGN KEY (id_category) REFERENCES category(id),
FOREIGN KEY (id_location) REFERENCES location(id)
ON UPDATE CASCADE
ON DELETE CASCADE
);

CREATE TABLE users(
id INTEGER AUTO_INCREMENT PRIMARY KEY,
full_name VARCHAR(255) NOT NULL,
is_active BOOLEAN NOT NULL DEFAULT TRUE,
id_role INTEGER,
email VARCHAR(255) UNIQUE NOT NULL,
password VARCHAR(225) NOT NULL,
created_at DATE NOT NULL DEFAULT (CURRENT_DATE),
update_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (id_role) REFERENCES roles(id)
ON UPDATE CASCADE
);

CREATE TABLE tickets(
id INTEGER AUTO_INCREMENT PRIMARY KEY,
id_event INTEGER,
id_user INTEGER NULL,
price DECIMAL(10,2),
created_at DATE NOT NULL DEFAULT (CURRENT_DATE),
update_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
QR TEXT,
FOREIGN KEY (id_event) REFERENCES events(id),
FOREIGN KEY (id_user) REFERENCES users(id) 
ON UPDATE CASCADE
ON DELETE SET NULL
);

